// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hls_top_HH_
#define _hls_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "transparent_crc.h"
#include "hls_top_crc32_tab.h"
#include "hls_top_g_5.h"

namespace ap_rtl {

struct hls_top : public sc_module {
    // Port declarations 7
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    hls_top(sc_module_name name);
    SC_HAS_PROCESS(hls_top);

    ~hls_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    hls_top_crc32_tab* crc32_tab_U;
    hls_top_g_5* g_5_U;
    transparent_crc* grp_transparent_crc_fu_165;
    sc_signal< sc_lv<16> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > g_6;
    sc_signal< sc_lv<8> > crc32_tab_address0;
    sc_signal< sc_logic > crc32_tab_ce0;
    sc_signal< sc_logic > crc32_tab_we0;
    sc_signal< sc_lv<32> > crc32_tab_q0;
    sc_signal< sc_lv<32> > g_3;
    sc_signal< sc_lv<32> > checksum_hercules;
    sc_signal< sc_lv<32> > crc32_context;
    sc_signal< sc_lv<3> > g_5_address0;
    sc_signal< sc_logic > g_5_ce0;
    sc_signal< sc_lv<32> > g_5_q0;
    sc_signal< sc_lv<32> > zext_ln58_fu_186_p1;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<9> > i_1_fu_196_p2;
    sc_signal< sc_lv<9> > i_1_reg_411;
    sc_signal< sc_lv<26> > trunc_ln2_reg_423;
    sc_signal< sc_lv<1> > icmp_ln57_fu_190_p2;
    sc_signal< sc_lv<1> > icmp_ln49_fu_236_p2;
    sc_signal< sc_lv<1> > icmp_ln49_reg_428;
    sc_signal< sc_lv<32> > crc_4_fu_277_p3;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln59_fu_247_p2;
    sc_signal< sc_lv<4> > j_fu_285_p2;
    sc_signal< sc_lv<1> > icmp_ln51_fu_314_p2;
    sc_signal< sc_lv<1> > icmp_ln51_reg_448;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > tmp_1_fu_296_p3;
    sc_signal< sc_lv<32> > l_18_fu_346_p1;
    sc_signal< sc_lv<32> > l_18_reg_453;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<2> > add_ln44_fu_364_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > g_3_load_reg_464;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<4> > i_fu_376_p2;
    sc_signal< sc_lv<4> > i_reg_472;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<1> > icmp_ln243_fu_370_p2;
    sc_signal< sc_lv<32> > g_5_load_reg_482;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > grp_transparent_crc_fu_165_ap_start;
    sc_signal< sc_logic > grp_transparent_crc_fu_165_ap_done;
    sc_signal< sc_logic > grp_transparent_crc_fu_165_ap_idle;
    sc_signal< sc_logic > grp_transparent_crc_fu_165_ap_ready;
    sc_signal< sc_lv<32> > grp_transparent_crc_fu_165_val_r;
    sc_signal< sc_lv<32> > grp_transparent_crc_fu_165_crc32_context_o;
    sc_signal< sc_logic > grp_transparent_crc_fu_165_crc32_context_o_ap_vld;
    sc_signal< sc_lv<8> > grp_transparent_crc_fu_165_crc32_tab_address0;
    sc_signal< sc_logic > grp_transparent_crc_fu_165_crc32_tab_ce0;
    sc_signal< sc_lv<9> > crc_reg_109;
    sc_signal< sc_lv<4> > j_0_i_reg_121;
    sc_signal< sc_lv<32> > crc_0_i_reg_132;
    sc_signal< sc_lv<2> > storemerge_i_reg_142;
    sc_signal< sc_lv<4> > i_0_reg_154;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > grp_transparent_crc_fu_165_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<64> > zext_ln66_fu_291_p1;
    sc_signal< sc_lv<64> > zext_ln245_fu_382_p1;
    sc_signal< sc_lv<32> > add_ln48_fu_334_p2;
    sc_signal< sc_lv<32> > add_ln52_fu_349_p2;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<32> > l_18_1_fu_78;
    sc_signal< sc_lv<31> > trunc_ln937_fu_206_p1;
    sc_signal< sc_lv<31> > add_ln49_fu_220_p2;
    sc_signal< sc_lv<30> > tmp_fu_226_p4;
    sc_signal< sc_lv<31> > crc_1_fu_253_p4;
    sc_signal< sc_lv<32> > crc_2_fu_263_p1;
    sc_signal< sc_lv<1> > trunc_ln59_fu_273_p1;
    sc_signal< sc_lv<32> > crc_3_fu_267_p2;
    sc_signal< sc_lv<26> > zext_ln51_fu_310_p1;
    sc_signal< sc_lv<32> > xor_ln250_fu_391_p2;
    sc_signal< sc_lv<16> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_ST_fsm_state1;
    static const sc_lv<16> ap_ST_fsm_state2;
    static const sc_lv<16> ap_ST_fsm_state3;
    static const sc_lv<16> ap_ST_fsm_state4;
    static const sc_lv<16> ap_ST_fsm_state5;
    static const sc_lv<16> ap_ST_fsm_state6;
    static const sc_lv<16> ap_ST_fsm_state7;
    static const sc_lv<16> ap_ST_fsm_state8;
    static const sc_lv<16> ap_ST_fsm_state9;
    static const sc_lv<16> ap_ST_fsm_state10;
    static const sc_lv<16> ap_ST_fsm_state11;
    static const sc_lv<16> ap_ST_fsm_state12;
    static const sc_lv<16> ap_ST_fsm_state13;
    static const sc_lv<16> ap_ST_fsm_state14;
    static const sc_lv<16> ap_ST_fsm_state15;
    static const sc_lv<16> ap_ST_fsm_state16;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_264D9248;
    static const sc_lv<3> ap_const_lv3_3;
    static const sc_lv<9> ap_const_lv9_100;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<31> ap_const_lv31_1;
    static const sc_lv<30> ap_const_lv30_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_EDB88320;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<4> ap_const_lv4_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln44_fu_364_p2();
    void thread_add_ln48_fu_334_p2();
    void thread_add_ln49_fu_220_p2();
    void thread_add_ln52_fu_349_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_crc32_tab_address0();
    void thread_crc32_tab_ce0();
    void thread_crc32_tab_we0();
    void thread_crc_1_fu_253_p4();
    void thread_crc_2_fu_263_p1();
    void thread_crc_3_fu_267_p2();
    void thread_crc_4_fu_277_p3();
    void thread_g_5_address0();
    void thread_g_5_ce0();
    void thread_grp_transparent_crc_fu_165_ap_start();
    void thread_grp_transparent_crc_fu_165_val_r();
    void thread_i_1_fu_196_p2();
    void thread_i_fu_376_p2();
    void thread_icmp_ln243_fu_370_p2();
    void thread_icmp_ln49_fu_236_p2();
    void thread_icmp_ln51_fu_314_p2();
    void thread_icmp_ln57_fu_190_p2();
    void thread_icmp_ln59_fu_247_p2();
    void thread_j_fu_285_p2();
    void thread_l_18_fu_346_p1();
    void thread_tmp_1_fu_296_p3();
    void thread_tmp_fu_226_p4();
    void thread_trunc_ln59_fu_273_p1();
    void thread_trunc_ln937_fu_206_p1();
    void thread_xor_ln250_fu_391_p2();
    void thread_zext_ln245_fu_382_p1();
    void thread_zext_ln51_fu_310_p1();
    void thread_zext_ln58_fu_186_p1();
    void thread_zext_ln66_fu_291_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
